# Generated by Django 3.2.4 on 2021-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=60)),
                ('servicedesc', models.TextField()),
                ('serviceimg', models.ImageField(upload_to='media')),
            ],
        ),
    ]
