# Generated by Django 3.2.4 on 2021-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_services_serviceimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='serviceimg',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
