# Generated by Django 3.2.4 on 2021-08-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_services_serviceimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('concern', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
    ]
