# Generated by Django 3.2.4 on 2021-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
